version: "3.9"

services:
  api:
    container_name: flask_hello_api
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.9-slim
        RUN pip install --no-cache-dir flask
        RUN apt-get update && apt-get install -y curl telnet procps
        COPY hello_flask_api.py /app/hello_flask_api.py
        EXPOSE 5000
        # CMD ["python", "/app/hello_flask_api.py","&"]
        # CMD ["python", "/app/hello_flask_api.py","&","curl", "localhost:5000/hello"]
        # CMD ["curl", "localhost:5000/hello"]
    # command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--reload"]
    command:
      python /app/hello_flask_api.py 
      # & ; curl localhost:5000/hello
      # curl localhost:5000/hello
      # tail -f

    ports:
      - "5000:5000"

    volumes:
      - .:/app
    working_dir: /app
    #   - /app/__pycache__
